_target_: transformers.AutoModelForSequenceClassification.from_pretrained
_convert_: object
pretrained_model_name_or_path: lxyuan/distilbert-base-multilingual-cased-sentiments-student
problem_type: single_label_classification
num_labels: 2
ignore_mismatched_sizes: True
